# -*- coding: utf-8 -*-
"""Saturation experiments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-hkExlVJX16NNC3MetqNTJ-IJdjQwzr
"""
from seaborn import color_palette

""" 
# Plot settings

"""

# %matplotlib inline
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
import seaborn as sns
import re
import matplotlib.ticker as ticker
import matplotlib as mpl
import omegaconf
from matplotlib.ticker import PercentFormatter, FormatStrFormatter
import glob
import statsmodels.formula.api as smf

custom_RS_18_RF = [3, 5, 7, 9, 11, 13, 17, 21, 25, 29, 37, 45, 53, 61, 77, 109, 133]

pytorch_RS_18_RF = [11, 19, 27, 35, 43, 51, 67, 83, 99, 115, 147, 179, 211, 243, 307, 371, 435]

resnets_rfs = [108, 110, 213, 318, 423, 1415, 1920, 3100]

vgg_rfs = [180, 181, 359, 537, 715]

vgg_inter_layers = ["features.4", "features.8", "features.11", "features.15",
                    "features.18", "features.21", "features.24", "features.28",
                    "features.31", "features.34", "features.37", "features.40",
                    "features.43", "features.46", "features.49"]

resnet_intermediate_layers = ["layer1.0.conv1", "layer1.0.conv2", "layer1.0.conv3", "layer1.0.shortcut.0",
                              "layer1.1.conv1", "layer1.1.conv2", "layer1.1.conv3", "layer1.2.conv1", "layer1.2.conv2",
                              "layer1.2.conv3", "layer2.0.conv1", "layer2.0.conv2", "layer2.0.conv3",
                              "layer2.0.shortcut.0", "layer2.1.conv1", "layer2.1.conv2", "layer2.1.conv3",
                              "layer2.2.conv1", "layer2.2.conv2", "layer2.2.conv3", "layer2.3.conv1", "layer2.3.conv2",
                              "layer2.3.conv3", "layer3.0.conv1", "layer3.0.conv2", "layer3.0.conv3",
                              "layer3.0.shortcut.0", "layer3.1.conv1", "layer3.1.conv2", "layer3.1.conv3",
                              "layer3.2.conv1", "layer3.2.conv2", "layer3.2.conv3", "layer3.3.conv1", "layer3.3.conv2",
                              "layer3.3.conv3", "layer3.4.conv1", "layer3.4.conv2", "layer3.4.conv3", "layer3.5.conv1",
                              "layer3.5.conv2", "layer3.5.conv3", "layer4.0.conv1", "layer4.0.conv2", "layer4.0.conv3",
                              "layer4.0.shortcut.0", "layer4.1.conv1", "layer4.1.conv2", "layer4.1.conv3",
                              "layer4.2.conv1", "layer4.2.conv2", "layer4.2.conv3"]
# in_block_layers_index= [resnet_intermediate_layers.index(l) for l in resnet_intermediate_layers if "conv1" in l or "conv2" in l]
# out_of_block_layer_index=[resnet_intermediate_layers.index(l) for l in resnet_intermediate_layers if "conv3" in l or "shortcut" in l]
resnet50_ticks = np.array(range(49))
resnet18_ticks = np.array(range(17))


def combine_mean_std(mean_and_std):
    mean, std = mean_and_std
    return "{} $\pm$ {}".format(mean, std)


def get_accuracy(el_string):
    new_string = el_string.split(" ")[0]
    list_of_string = re.findall("\d+\.\d+", el_string)
    return float(list_of_string[0])


# fs = 12
# fig_size = (6, 5)
# sns.reset_orig()
# sns.reset_defaults()
# matplotlib.rc_file_defaults()

in_block_layers_index = [1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25, 26, 28, 29, 31, 32, 34, 35, 37,
                         38, 40,
                         41, 43, 44, 46, 47]
out_of_block_layer_index = [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

in_block_layers = [1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25, 26, 28, 29, 31, 32, 34, 35, 37, 38, 40,
                   41, 43, 44, 46, 47]
out_block_layers = [0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

resnets_rfs_values = [108, 110, 213, 318, 423, 538, 645, 752, 859, 1415, 1920, 3100]

resnet_rfs_keys = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

resnets_rfs = dict(zip(resnet_rfs_keys, resnets_rfs_values))

small_resnets_rfs_values = [30, 39, 129, 174, 309, 399, 487, 568]
small_resnets_rfs_keys = [3, 4, 5, 6, 7, 8, 9, 10]

small_resnets_rfs = dict(zip(small_resnets_rfs_keys, small_resnets_rfs_values))

vgg_rfs = [180, 181, 359, 537, 715]

# plt.rcParams.update({
#     "axes.linewidth": 0.5,
#     'axes.edgecolor': 'black',
#     "grid.linewidth": 0.4,
#     "lines.linewidth": 1,
#     'xtick.bottom': True,
#     'xtick.color': 'black',
#     "xtick.direction": "out",
#     "xtick.major.size": 3,
#     "xtick.major.width": 0.5,
#     "xtick.minor.size": 1.5,
#     "xtick.minor.width": 0.5,
#     'ytick.left': True,
#     'ytick.color': 'black',
#     "ytick.major.size": 3,
#     "ytick.major.width": 0.5,
#     "ytick.minor.size": 1.5,
#     "ytick.minor.width": 0.5,
#     "figure.figsize": [3.3, 2.5],
#     'axes.labelsize': 'xx-large',
#     'axes.titlesize': 'xx-large',
#     "text.usetex": True,
#     "font.family": "serif",
#     # "text.tex.preamble": r"\usepackage{bm} \usepackage{amsmath}",
# })

fs = 12
# fig_size = (3, 2.5) # For the large_input_experiments_only_sgd_paper()
# fig_size = (4 , 2.5) # For the vgg19_cifar10_saturation()
fig_size = (7, 3.5)  # For the resnet50_dilation_cifar10_saturation()

# fig_size = (5 , 5) # For the vgg19_cifar10_saturation()
legends_multiplier = 1.1
# labels_multiplier = 1 # For the large_input_experiments_only_sgd_paper()
# ticks_multiplier = 0.8 # For the large_input_experiments_only_sgd_paper()

labels_multiplier = 1.3  # For the vgg19_cifar10_saturation()
ticks_multiplier = 1.2  # For the vgg19_cifar10_saturation()
plt.rcParams.update({
    "axes.linewidth": 0.5,
    'axes.edgecolor': 'black',
    "grid.linewidth": 0.4,
    "lines.linewidth": 1,
    'xtick.bottom': True,
    'xtick.color': 'black',
    "xtick.direction": "out",
    "xtick.major.size": 3,
    "xtick.major.width": 0.5,
    "xtick.minor.size": 1.5,
    "xtick.minor.width": 0.5,
    'ytick.left': True,
    'ytick.color': 'black',
    "ytick.major.size": 3,
    "ytick.major.width": 0.5,
    "ytick.minor.size": 1.5,
    "ytick.minor.width": 0.5,
    # "figure.figsize": [3.3, 2.5],
    'axes.labelsize': 'xx-large',
    'axes.titlesize': 'xx-large',
    "text.usetex": True,
    "font.family": "serif",
    "text.latex.preamble": r"\usepackage{bm} \usepackage{amsmath}",
})

from typing import Callable, Dict, List, Tuple


def extract_layer_stat(df,
                       epoch=19,
                       primary_metric=None,
                       stat='saturation',
                       state_mode="train") -> Tuple[pd.DataFrame, float]:
    """
    Extracts a specific statistic for a single epoch from a result dataframe as produced by the CSV-writer
    :param df: The dataframe produced by a CSVWriter
    :param epoch: Epoch to filter by
    :param primary_metric: Primary metric for performance evaluation (optional)
    :param stat: The statistic to match. Must be a substring matching all columns belonging to stat statistic like "saturation"
    :return: A dataframe with a single row, corresponding to the epoch containing only the columns that contain the substring
    described in the stat-parameter in their name. Second return value is the primary metric value
    """
    cols = list(df.columns)
    train_cols = [
        col for col in cols
        if state_mode in col and 'accuracy' not in col and stat in col
    ]
    if not np.any(epoch == df.index.values):
        raise ValueError(
            f'Epoch {epoch} could not be recoreded, dataframe has only the following indices: {df.index.values}'
        )
    epoch_df = df[df.index.values == epoch]
    pm = None if primary_metric is None else epoch_df[primary_metric].values[0]
    epoch_df = epoch_df[train_cols]
    return epoch_df, pm


def depth_scaled_saturation(layer_values):
    scaled_depth_indexes = np.array((range(1, len(layer_values) + 1))) / (len(layer_values))
    return layer_values * scaled_depth_indexes


def diverse_pooling_saturation_summary(base_folder, model_names, rf_levels=(1, 2, 3, 4), seeds=(0, 1, 2),
                                       dataset="cifar10", name="recording_diverse_pooling_100_no_ffcv",
                                       pruning_rate=0.0, epoch=0,
                                       save_path="saturation_diverse_pooling/diverse_pooling_train_saturation_summary.csv"):
    """
    Walks base_folder for the per-solution saturation CSVs produced by saturation_calculation.py
    (one row per file, named "<model>_<rf_level>_<dataset>_<name>_pr_<pruning_rate>_saturation_trained_seed_<seed>.csv"),
    and for each (model, rf_level, seed) observation extracts the train-time saturation of every
    layer at the given epoch via extract_layer_stat(), then averages across layers. Writes one row
    per observation (model, rf_level, seed, avg_train_saturation, std_train_saturation) to save_path.
    """
    rows = []
    missing = []
    for model in model_names:
        for rf_level in rf_levels:
            for seed in seeds:
                search_string = "{}/**/{}_{}_{}_{}_pr_{}_saturation_trained_seed_{}.csv".format(
                    base_folder, model, rf_level, dataset, name, pruning_rate, seed)
                matches = glob.glob(search_string, recursive=True)
                if not matches:
                    missing.append((model, rf_level, seed))
                    continue
                if len(matches) > 1:
                    print("WARNING: multiple files matched for {} rf_level={} seed={}, using the first one: {}".format(
                        model, rf_level, seed, matches))

                if model.startswith("resnet50_"):
                    model_type = "Resnet50"
                    pooling = model[len("resnet50_"):]
                elif model.startswith("vgg19_"):
                    model_type = "vgg19"
                    pooling = model[len("vgg19_"):]
                else:
                    print(f"WARNING: could not determine model type/pooling for model name '{model}'")
                    model_type = None
                    pooling = None

                df = pd.read_csv(matches[0], delimiter=";", index_col=0)
                epoch_df, _ = extract_layer_stat(df, epoch=epoch, primary_metric=None, stat="saturation",
                                                 state_mode="train")
                layer_values = epoch_df.values[0].astype(float)

                depth_scaled_layer_values = depth_scaled_saturation(layer_values)

                if model.startswith("resnet50_"):
                    in_block_layers_values = layer_values[in_block_layers_index]
                    depth_scaled_inblock_values = depth_scaled_saturation(in_block_layers_values)

                    out_block_layers_values = layer_values[out_of_block_layer_index]
                    depth_scaled_outblock_values = depth_scaled_saturation(out_block_layers_values)

                    rows.append({
                        "model": model,
                        "model type": model_type,
                        "pooling": pooling,
                        "rf_level": rf_level,
                        "seed": seed,
                        "n_layers": len(layer_values),
                        "avg_train_saturation": float(np.mean(layer_values)),
                        "std_train_saturation": float(np.std(layer_values, ddof=1)),
                        "avg_train_saturation_inblock": float(np.mean(in_block_layers_values)),
                        "std_train_saturation_inblock": float(np.std(in_block_layers_values, ddof=1)),
                        "avg_train_saturation_outlock": float(np.mean(out_block_layers_values)),
                        "std_train_saturation_outblock": float(np.std(out_block_layers_values, ddof=1)),
                        "avg_depth_scaled_train_saturation": float(np.mean(depth_scaled_layer_values)),
                        "std_depth_scaled_train_saturation": float(np.mean(depth_scaled_layer_values)),
                        "avg_depth_scaled_train_saturation_inblock": float(np.mean(depth_scaled_inblock_values)),
                        "std_depth_scaled_train_saturation_inblock": float(np.std(depth_scaled_inblock_values, ddof=1)),
                        "avg_depth_scaled_train_saturation_outlock": float(np.mean(depth_scaled_outblock_values)),
                        "std_depth_scaled_train_saturation_outblock": float(
                            np.std(depth_scaled_outblock_values, ddof=1))
                    })
                else:
                    rows.append({
                        "model": model,
                        "model type": model_type,
                        "pooling": pooling,
                        "rf_level": rf_level,
                        "seed": seed,
                        "n_layers": len(layer_values),
                        "avg_train_saturation": float(np.mean(layer_values)),
                        "std_train_saturation": float(np.std(layer_values, ddof=1)),
                        "avg_depth_scaled_train_saturation": float(np.mean(depth_scaled_layer_values)),
                        "std_depth_scaled_train_saturation": float(np.mean(depth_scaled_layer_values)),
                    })

    if missing:
        print("WARNING: {} missing (model, rf_level, seed) observations:".format(len(missing)))
        for m in missing:
            print("   ", m)

    summary_df = pd.DataFrame(rows)
    summary_df.to_csv(save_path, index=False)
    print("Wrote {} rows to {}".format(len(summary_df), save_path))
    return summary_df


def resnet50_cifar10_dilation_different_rf(data_folder, save_folder, model_type="_dilation",
                                           name="recording_dilation_100_no_ffcv"):
    resnet_all_layers = ["conv1", "layer1.0.conv1", "layer1.0.conv2", "layer1.0.conv3", "layer1.0.shortcut.0",
                         "layer1.1.conv1", "layer1.1.conv2", "layer1.1.conv3", "layer1.2.conv1", "layer1.2.conv2",
                         "layer1.2.conv3", "layer2.0.conv1", "layer2.0.conv2", "layer2.0.conv3",
                         "layer2.0.shortcut.0", "layer2.1.conv1", "layer2.1.conv2", "layer2.1.conv3",
                         "layer2.2.conv1", "layer2.2.conv2", "layer2.2.conv3", "layer2.3.conv1", "layer2.3.conv2",
                         "layer2.3.conv3", "layer3.0.conv1", "layer3.0.conv2", "layer3.0.conv3",
                         "layer3.0.shortcut.0", "layer3.1.conv1", "layer3.1.conv2", "layer3.1.conv3",
                         "layer3.2.conv1", "layer3.2.conv2", "layer3.2.conv3", "layer3.3.conv1", "layer3.3.conv2",
                         "layer3.3.conv3", "layer3.4.conv1", "layer3.4.conv2", "layer3.4.conv3", "layer3.5.conv1",
                         "layer3.5.conv2", "layer3.5.conv3", "layer4.0.conv1", "layer4.0.conv2", "layer4.0.conv3",
                         "layer4.0.shortcut.0", "layer4.1.conv1", "layer4.1.conv2", "layer4.1.conv3",
                         "layer4.2.conv1", "layer4.2.conv2", "layer4.2.conv3", "linear"]
    in_block_layers_index = [resnet_all_layers.index(l) for l in resnet_all_layers if ".conv1" in l or ".conv2" in l]
    out_of_block_layer_index = [resnet_all_layers.index(l) for l in resnet_all_layers if
                                ".conv3" in l or ".shortcut" in l or "conv1" == l]

    # resnets_rfs = [108, 110, 213, 318, 423, 1415, 1920, 3100]
    # resnets_rfs =[ 1,54, 107, 159, 655, 907, 1497]
    resnets_rfs = [1, 54, 107, 159]
    conversion_rf_dict = {1: "107 (no dilation)", 54: 213, 107: 318, 159: 423, 655: 1415, 907: 1920, 1497: 3100}
    all_dfs = []
    for level in resnets_rfs:

        search_string = "{}/resnet50{}_{}_cifar10_{}*saturation_trained*seed_0.csv".format(data_folder, model_type,
                                                                                           level, name,
                                                                                           )
        print(search_string)
        list_of_csvs = list(glob.glob(search_string))
        # This should be only one file_name
        for file_name in list_of_csvs:
            temp_saturation_df = pd.read_csv(file_name, delimiter=";")
            temp_saturation_df["RF"] = [level] * len(temp_saturation_df)
            all_dfs.append(temp_saturation_df)
    all_rf_df = pd.concat(all_dfs)

    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")

    unique_RF = all_rf_df["RF"].unique()
    num_colors = len(unique_RF)
    cm = mpl.cm.get_cmap(name='magma')
    currentColors = [cm(1. * i / num_colors) for i in range(num_colors)]

    colors = ["blue", "red", "green", "orange", "yellow"]
    # optimisers = ["SGD"]

    # for i, ax in enumerate(axs.flat):
    for i, color in enumerate(currentColors):
        current_df = all_rf_df[all_rf_df["RF"] == unique_RF[i]]
        current_df = current_df.mean(axis=0).to_frame().T

        epoch_df_dense, pm = extract_layer_stat(current_df,
                                                epoch=0,
                                                primary_metric=None,
                                                stat='saturation',
                                                state_mode="train")

        # plot_saturation(epoch_df=epoch_df_dense, ax=ax, log=False, color=color, label=f"{unique_RF[i]}", ewma=False,
        #                 window=5,index_to_keep=in_block_layers_index)
        ax.scatter(x=range(len(in_block_layers_index)), y=epoch_df_dense.values[0][in_block_layers_index], color=color,
                   marker="o", label=f"{conversion_rf_dict[unique_RF[i]]}")
    # ax.set_title(f"{unique_RF[i]}")
    ax.grid(ls="--", alpha=0.5)
    # ax.set_xlabel("")
    # ax.set_ylabel("")
    ax.set_xticks(range(len(in_block_layers_index)), in_block_layers_index, color="k")
    ax.set_yticks([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], color="k")
    # ax.set_yticks([-3, -2.5, -2, -1.5, -1], [-3, -2.5, -2, -1.5, -1], color="k")
    # ax.set_xticks([])
    ax.set_xlabel("Layer", fontsize=fs * labels_multiplier)
    ax.set_ylabel("Saturation", fontsize=fs * labels_multiplier)
    ax.xaxis.set_major_locator(ticker.MultipleLocator(10))
    ax.xaxis.set_minor_locator(ticker.MultipleLocator(5))

    ax.tick_params(axis="both", labelsize=fs * ticks_multiplier)
    # ax.tick_params(axis="x", labelcolor="w")
    ax.legend()
    plt.savefig(f"{save_folder}/resnet50{model_type}_cifar10_saturation_inblock_v1.pdf",
                bbox_inches="tight")

    plt.close()
    ##################################
    #       Out of block
    ##################################
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    unique_RF = all_rf_df["RF"].unique()
    num_colors = len(unique_RF)
    cm = mpl.cm.get_cmap(name='magma')
    currentColors = [cm(1. * i / num_colors) for i in range(num_colors)]

    # colors = ["blue","red","green","yellow"]
    colors = ["blue", "red", "green", "orange", "yellow"]
    # optimisers = ["SGD"]

    # for i, ax in enumerate(axs.flat):
    for i, color in enumerate(currentColors):
        current_df = all_rf_df[all_rf_df["RF"] == unique_RF[i]]
        current_df = current_df.mean(axis=0).to_frame().T

        epoch_df_dense, pm = extract_layer_stat(current_df,
                                                epoch=0,
                                                primary_metric=None,
                                                stat='saturation',
                                                state_mode="train")

        # plot_saturation(epoch_df=epoch_df_dense, ax=ax, log=False, color=color, label=f"{unique_RF[i]}", ewma=False,
        #                 window=5,index_to_keep=out_of_block_layer_index)
        ax.scatter(x=range(len(out_of_block_layer_index)), y=epoch_df_dense.values[0][out_of_block_layer_index],
                   color=color, marker="o", label=f"{conversion_rf_dict[unique_RF[i]]}")
    # ax.set_title(f"{unique_RF[i]}")
    ax.grid(ls="--", alpha=0.5)
    # ax.set_xlabel("")
    # ax.set_ylabel("")
    ax.set_xticks(range(len(out_of_block_layer_index)), out_of_block_layer_index, color="k")
    ax.set_yticks([0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8], color="k")
    # ax.set_yticks([-3, -2.5, -2, -1.5, -1], [-3, -2.5, -2, -1.5, -1], color="k")
    ax.set_xlabel("Layer", fontsize=fs * labels_multiplier)
    ax.set_ylabel("Saturation", fontsize=fs * labels_multiplier)
    ax.xaxis.set_major_locator(ticker.MultipleLocator(5))
    ax.xaxis.set_minor_locator(ticker.MultipleLocator(3))
    # ax.set_xticks([])
    ax.tick_params(axis="both", labelsize=fs * ticks_multiplier)
    ax.legend()
    # ax.tick_params(axis="x", labelcolor="w")
    plt.savefig(f"{save_folder}/resnet50{model_type}_cifar10_saturation_outblock_v1.pdf",
                bbox_inches="tight")

    plt.close()


def plot_saturation_relationships(save_folder):
    df = pd.read_csv("diverse_pooling_pruning_saturation_in-out_block_layers_combined.csv", ",")
    df_09 = df[df["pruning_rate"] == 0.9]
    # local_df = df_09[df_09["model"].str.contains("resnet50")]
    # fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    # Rename columns directly in your data presentation step
    renamed_df = df_09.rename(columns={
        "saturation_depth_scaled_mean": r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
        "rf_level": "RF Level",
        "delta_mean": r"$\Delta (Dense - Pruned)$",
        "pooling": "Pooling method"
    })

    # g=sns.pairplot(df_09,x_vars=["saturation_depth_scaled_mean","rf_level"],y_vars="delta_mean",hue="pooling",palette="deep")
    g = sns.pairplot(renamed_df,
                     x_vars=[r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$", "Pooling method"],
                     y_vars=r"$\Delta (Dense - Pruned)$", hue="RF Level", palette="deep")
    # g.set_axis_labels(x_var_names=["$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$","RF Level"], y_var_names=["$\Delta (Dense - Pruned)$"])
    # ax.set_xlabel( r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",fontsize=fs*labels_multiplier)
    # ax.set_ylabel("$\Delta (Dense - Pruned)$",fontsize=fs*labels_multiplier)
    # ax.legend()
    plt.savefig(f"{save_folder}/comparisons_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9_accuracy_V2.pdf",
                bbox_inches="tight")

    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.barplot(renamed_df, ax=ax, x="RF Level",
                y=r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$", hue="Pooling method")
    # ax.legend()
    plt.savefig(f"{save_folder}/comparisons_BAR_diverse_pooling_cifar10_depth_scaled_saturation_pr_0.9.pdf",
                bbox_inches="tight")
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.barplot(renamed_df, ax=ax, x="RF Level", y=r"$\Delta (Dense - Pruned)$", hue="Pooling method")
    # ax.legend()
    plt.savefig(f"{save_folder}/comparisons_BAR_diverse_pooling_cifar10_delta_accuracy_pr_0.9.pdf",
                bbox_inches="tight")
    ## resnet50
    df = renamed_df[renamed_df["model"].str.contains("resnet50")]
    g = sns.pairplot(df,
                     x_vars=[r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$", "Pooling method"],
                     y_vars=r"$\Delta (Dense - Pruned)$", hue="RF Level", palette="deep")
    plt.savefig(
        f"{save_folder}/resnet50_comparisons_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9_accuracy.pdf",
        bbox_inches="tight")
    g = sns.pairplot(df, x_vars=["Pooling method"],
                     y_vars=r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$", hue="RF Level",
                     palette="deep")
    plt.savefig(f"{save_folder}/resnet50_comparisons_diverse_pooling_cifar10_depth_scaled_saturation_pr_0.9.pdf",
                bbox_inches="tight")

    ## VGG19
    df = renamed_df[renamed_df["model"].str.contains("vgg19")]
    g = sns.pairplot(df,
                     x_vars=[r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$", "Pooling method"],
                     y_vars=r"$\Delta (Dense - Pruned)$", hue="RF Level", palette="deep")
    plt.savefig(
        f"{save_folder}/vgg19_comparisons_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9_accuracy.pdf",
        bbox_inches="tight")
    g = sns.pairplot(df, x_vars=["Pooling method"],
                     y_vars=r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$", hue="RF Level",
                     palette="deep")
    plt.savefig(f"{save_folder}/vgg19_comparisons_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9.pdf",
                bbox_inches="tight")


def plot_diverse_pooling_results(save_folder, ):
    # df = pd.read_csv( "diverse_pooling_pruning_saturation_combined.csv",",")
    df = pd.read_csv("diverse_pooling_pruning_saturation_in-out_block_layers_combined.csv", sep=",")
    df_09 = df[df["pruning_rate"] == 0.9]
    df_08 = df[df["pruning_rate"] == 0.8]
    df_07 = df[df["pruning_rate"] == 0.7]
    color_palette = "crest"

    num_colors = 4
    cm = mpl.cm.get_cmap(name='magma')
    currentColors = [cm(1. * i / num_colors) for i in range(num_colors)]
    #  For pruning rate 0.9
    ## For resnet50 model
    ### Inblock layers
    local_df = df_09[df_09["model"].str.contains("resnet50")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_inblock_mean", y="delta_mean", hue="rf_level",
                    style="pooling", palette=color_palette)
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    ax.legend()
    plt.savefig(
        f"{save_folder}/resnet50_inblock_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9_accuracy.pdf",
        bbox_inches="tight")

    ### Outblock layers
    local_df = df_09[df_09["model"].str.contains("resnet50")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_outblock_mean", y="delta_mean", hue="rf_level",
                    style="pooling", palette=color_palette)
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    ax.legend()
    plt.savefig(
        f"{save_folder}/resnet50_outblock_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9_accuracy.pdf",
        bbox_inches="tight")

    ### All layers

    local_df = df_09[df_09["model"].str.contains("resnet50")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_mean", y="delta_mean", hue="rf_level", style="pooling",
                    palette=color_palette)
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    ax.legend()
    plt.savefig(f"{save_folder}/resnet50_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9_accuracy.pdf",
                bbox_inches="tight")
    ## For vgg19 model

    local_df = df_09[df_09["model"].str.contains("vgg19")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_mean", y="delta_mean", hue="rf_level", style="pooling",
                    palette=color_palette)

    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    plt.savefig(f"{save_folder}/vgg19_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.9_accuracy.pdf",
                bbox_inches="tight")

    #  For pruning rate 0.8

    ## For resnet50 model
    local_df = df_08[df_08["model"].str.contains("resnet50")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_mean", y="delta_mean", hue="rf_level", style="pooling",
                    palette=color_palette)
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    plt.savefig(f"{save_folder}/resnet50_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.8_accuracy.pdf",
                bbox_inches="tight")

    ## For vgg19 model

    local_df = df_08[df_08["model"].str.contains("vgg19")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_mean", y="delta_mean", hue="rf_level", style="pooling",
                    palette=color_palette)
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    plt.savefig(f"{save_folder}/vgg19_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.8_accuracy.pdf",
                bbox_inches="tight")

    #  For pruning rate 0.7
    ## For resnet50 model
    local_df = df_07[df_07["model"].str.contains("resnet50")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_mean", y="delta_mean", hue="rf_level", style="pooling",
                    palette=color_palette)
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    plt.savefig(f"{save_folder}/resnet50_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.7_accuracy.pdf",
                bbox_inches="tight")

    ## For vgg19 model

    local_df = df_07[df_07["model"].str.contains("vgg19")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="saturation_depth_scaled_mean", y="delta_mean", hue="rf_level", style="pooling",
                    palette=color_palette)
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("$\Delta (Dense - Pruned)$", fontsize=fs * labels_multiplier)
    plt.savefig(f"{save_folder}/vgg19_diverse_pooling_cifar10_depth_scaled_saturation_VS_pr_0.7_accuracy.pdf",
                bbox_inches="tight")


def analysis_pooling_methods():
    """
    This function is to analyze statistically the effect of different parts in prunability and saturation
    """

    df = pd.read_csv("diverse_pooling_pruning_saturation_per_seed_combined.csv", sep=",")

    df = df.rename(columns={
        "avg_depth_scaled_train_saturation": r"scaled_saturation",
        # "rf_level": "RF Level",
        # "delta_mean":r"$\Delta (Dense - Pruned)$",
        # "pooling":"Pooling method"
    })

    print("==================================================")
    print("  Not separating by model or Pruning rate")
    print("==================================================")

    # 1. Ensure RF is numeric/ordinal (e.g., 1, 2, 3, 4 or actual pixel sizes)
    df['RF_ordinal'] = df['rf_level'].astype(float)

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~ scaled_saturation + RF_ordinal + C(pooling)',
        data=df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    # Export all summary tables into an Excel workbook with multiple sheets
    with pd.ExcelWriter('full_model_all_models_all_pr.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')
        # now the outcome one
        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')

    print("==================================================")
    print("  Separating by model not Pruning rate")
    print("==================================================")

    print("==================================================")
    print("                    RESNET50")
    print("==================================================")

    current_df = df[df["model"].str.contains("resnet50")]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~ scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    # Export all summary tables into an Excel workbook with multiple sheets
    with pd.ExcelWriter('full_model_resnet50_all_pr.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')
        # now the outcome one
        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')

    print("==================================================")
    print("               VGG19")
    print("==================================================")

    current_df = df[df["model"].str.contains("vgg19")]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~ scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    # Export all summary tables into an Excel workbook with multiple sheets

    with pd.ExcelWriter('full_model_vgg19_all_pr.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

        # now the outcome one

        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')

    print("\n\n")
    print("==================================================")
    print("  Separating by model and pruning rate of 0.9")
    print("==================================================")

    print("==================================================")
    print("                    RESNET50")
    print("==================================================")

    current_df = df[df["model"].str.contains("resnet50")]
    current_df = current_df[current_df["pruning_rate"] == 0.9]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~ scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    with pd.ExcelWriter('full_model_resnet50_pr_0.9.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

        # now the outcome one

        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')

    print("==================================================")
    print("               VGG19")
    print("==================================================")

    current_df = df[df["model"].str.contains("vgg19")]
    current_df = current_df[current_df["pruning_rate"] == 0.9]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~ scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    with pd.ExcelWriter('full_model_vgg19_pr_0.9.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

        # now the outcome one

        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')
    print("\n\n")
    print("==================================================")
    print("  Separating by model and pruning rate of 0.8")
    print("==================================================")

    print("==================================================")
    print("                    RESNET50")
    print("==================================================")

    current_df = df[df["model"].str.contains("resnet50")]
    current_df = current_df[current_df["pruning_rate"] == 0.8]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~  scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    with pd.ExcelWriter('full_model_resnet50_pr_0.8.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

        # now the outcome one

        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')
    print("==================================================")
    print("               VGG19")
    print("==================================================")

    current_df = df[df["model"].str.contains("vgg19")]
    current_df = current_df[current_df["pruning_rate"] == 0.8]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~  scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    with pd.ExcelWriter('full_model_vgg19_pr_0.8.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

        # now the outcome one

        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')

    print("\n\n")
    print("==================================================")
    print("  Separating by model and pruning rate of 0.7")
    print("==================================================")

    print("==================================================")
    print("                    RESNET50")
    print("==================================================")

    current_df = df[df["model"].str.contains("resnet50")]
    current_df = current_df[current_df["pruning_rate"] == 0.7]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~  scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    with pd.ExcelWriter('full_model_resnet50_pr_0.7.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

        # now the outcome one

        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')

    print("==================================================")
    print("               VGG19")
    print("==================================================")

    current_df = df[df["model"].str.contains("vgg19")]
    current_df = current_df[current_df["pruning_rate"] == 0.7]

    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_mediator = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    print("==================================================")
    print("  MODEL 1: MEDIATOR EQUATION (Saturation ~ X * M)")
    print("==================================================")
    print(model_mediator.summary())

    # 3. Model 2: Direct Effect Outcome Equation (c'-paths & b-path)
    # Tests if RF, Pooling, and RF*Pooling directly influence Prunability
    # WHEN CONTROLLING FOR Saturation
    model_outcome = smf.ols(
        'delta~  scaled_saturation + RF_ordinal + C(pooling)',
        data=current_df
    ).fit()

    print("\n==================================================")
    print("  MODEL 2: OUTCOME EQUATION (Prunability ~ X * M + Saturation)")
    print("==================================================")
    print(model_outcome.summary())

    with pd.ExcelWriter('full_model_vgg19_pr_0.7.xlsx') as writer:
        model_mediator.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model_mediator.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model_mediator.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

        # now the outcome one

        model_outcome.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Outcome')
        model_outcome.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Outcome')
        model_outcome.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Outcome')


def analysis_pooling_methods_fine_tuned():
    df = pd.read_csv("diverse_pooling_finetune_raw_combined.csv", sep=",")

    # df = df.rename(columns={
    #     "avg_depth_scaled_train_saturation": r"scaled_saturation",
    #     # "rf_level": "RF Level",
    #     # "delta_mean":r"$\Delta (Dense - Pruned)$",
    #     # "pooling":"Pooling method"
    # })

    print("==================================================")
    print("  Not separating by model or Pruning rate")
    print("==================================================")

    # 1. Ensure RF is numeric/ordinal (e.g., 1, 2, 3, 4 or actual pixel sizes)
    df['RF_ordinal'] = df['rf_level'].astype(float)

    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model = smf.ols(
        'fine_tuned_acc~  RF_ordinal + C(pooling) + C(model)+ RF_ordinal *C(model)*C(pooling) + RF_ordinal * C(pooling)',
        data=df
    ).fit()

    with pd.ExcelWriter('ft_accuracy_model_all_models.xlsx') as writer:
        model.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

    # Resnet50
    current_df = df[df["model"].str.contains("resnet50")]
    model = smf.ols(
        'fine_tuned_acc~  RF_ordinal + C(pooling) + C(model)+  RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    with pd.ExcelWriter('ft_accuracy_model_resnet50.xlsx') as writer:
        model.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

    # Vgg19
    current_df = df[df["model"].str.contains("vgg19")]
    model = smf.ols(
        'fine_tuned_acc~  RF_ordinal + C(pooling) + C(model)+  RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    with pd.ExcelWriter('ft_accuracy_model_vgg19.xlsx') as writer:
        model.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

def analysis_pooling_methods_one_shot():
    df = pd.read_csv("diverse_pooling_finetune_raw_combined.csv", sep=",")

    # df = df.rename(columns={
    #     "avg_depth_scaled_train_saturation": r"scaled_saturation",
    #     # "rf_level": "RF Level",
    #     # "delta_mean":r"$\Delta (Dense - Pruned)$",
    #     # "pooling":"Pooling method"
    # })

    print("==================================================")
    print("  Not separating by model or Pruning rate")
    print("==================================================")

    # 1. Ensure RF is numeric/ordinal (e.g., 1, 2, 3, 4 or actual pixel sizes)
    df['RF_ordinal'] = df['rf_level'].astype(float)

    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model = smf.ols(
        'one_shot_acc~  RF_ordinal + C(pooling) + C(model)+ RF_ordinal *C(model)*C(pooling) + RF_ordinal * C(pooling)',
        data=df
    ).fit()

    with pd.ExcelWriter('OS_accuracy_model_all_models.xlsx') as writer:
        model.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

    # Resnet50
    current_df = df[df["model"].str.contains("resnet50")]
    model = smf.ols(
        'one_shot_acc~  RF_ordinal + C(pooling) + C(model)+  RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    with pd.ExcelWriter('OS_accuracy_model_resnet50.xlsx') as writer:
        model.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

    # Vgg19
    current_df = df[df["model"].str.contains("vgg19")]
    model = smf.ols(
        'one_shot_acc~  RF_ordinal + C(pooling) + C(model)+  RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    with pd.ExcelWriter('OS_accuracy_model_vgg19.xlsx') as writer:
        model.summary2().tables[0].to_excel(writer, sheet_name='Model Specs Mediator')
        model.summary2().tables[1].to_excel(writer, sheet_name='Coefficients Mediator')
        model.summary2().tables[2].to_excel(writer, sheet_name='Residuals & Diagnostics Mediator')

def decide_type_of_model():
    df = pd.read_csv("diverse_pooling_pruning_saturation_per_seed_combined.csv", sep=",")

    df = df.rename(columns={
        "avg_depth_scaled_train_saturation": r"scaled_saturation",
        # "rf_level": "RF Level",
        # "delta_mean":r"$\Delta (Dense - Pruned)$",
        # "pooling":"Pooling method"
    })

    print("==================================================")
    print("  Not separating by model or Pruning rate")
    print("==================================================")

    # 1. Ensure RF is numeric/ordinal (e.g., 1, 2, 3, 4 or actual pixel sizes)
    df['RF_ordinal'] = df['rf_level'].astype(float)

    current_df = df[df["model"].str.contains("resnet50")]
    current_df = current_df[current_df["pruning_rate"] == 0.7]
    # 2. Model 1: Mediator Equation (a-paths)
    # Tests if RF, Pooling (4 levels), and their interaction influence Saturation
    model_simple = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) + RF_ordinal * C(pooling)',
        data=current_df
    ).fit()

    model_complex = smf.ols(
        'scaled_saturation ~  RF_ordinal + C(pooling) ',
        data=current_df
    ).fit()
    # Compare AIC and BIC
    print(f"Simple Model  - AIC: {model_simple.aic:.2f}, BIC: {model_simple.bic:.2f}")
    print(f"Complex Model - AIC: {model_complex.aic:.2f}, BIC: {model_complex.bic:.2f}")

    print("###################################################")
    print("\t\t\tNow for delta (prunability)")
    print("=====================================================")
    model_simple = smf.ols(
        'delta~ scaled_saturation + RF_ordinal + C(pooling)',
        data=df
    ).fit()

    model_complex = smf.ols(
        'delta~ RF_ordinal * C(pooling) + scaled_saturation + RF_ordinal + C(pooling)',
        data=df
    ).fit()
    # Compare AIC and BIC
    print(f"Simple Model  - AIC: {model_simple.aic:.2f}, BIC: {model_simple.bic:.2f}")
    print(f"Complex Model - AIC: {model_complex.aic:.2f}, BIC: {model_complex.bic:.2f}")

def plotting_second_order_saturation_OS_accuracy(save_folder):

    df = pd.read_csv("second_order_pruning_saturation_one_shot_combined.csv", sep=",")
    num_colors = 4
    cm = mpl.cm.get_cmap(name='magma')
    currentColors = [cm(1. * i / num_colors) for i in range(num_colors)]
    #  For pruning rate 0.9
    ## For resnet50 model
    ### Inblock layers
    local_df = df[df["model"].str.contains("resnet50")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="scaled_saturation_mean", y="one_shot_acc", hue="rf_level",
                    style="optimisation_method",palette="deep")
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("Pruned Accuracy", fontsize=fs * labels_multiplier)
    ax.legend()
    plt.savefig(
        f"{save_folder}/resnet50_second_order_saturation_vs_pruned_accuracy.pdf",
        bbox_inches="tight")

    local_df = df[df["model"].str.contains("vgg19")]
    fig, ax = plt.subplots(1, 1, figsize=fig_size, sharey=True, sharex=True, layout="tight")
    sns.scatterplot(local_df, ax=ax, x="scaled_saturation_mean", y="one_shot_acc", hue="rf_level",
                    style="optimisation_method",palette="deep")
    ax.set_xlabel(r"$\frac{\text{Depth}_i}{\max_i \text{Depth}_i}\cdot\text{Saturation}$",
                  fontsize=fs * labels_multiplier)
    ax.set_ylabel("Pruned Accuracy", fontsize=fs * labels_multiplier)
    ax.legend()
    plt.savefig(
        f"{save_folder}/vgg19_second_order_saturation_vs_pruned_accuracy.pdf",
        bbox_inches="tight")
if __name__ == '__main__':
    # resnet50_cifar10_dilation_different_rf("saturation_dilation_maxpool/cifar10/resnet50", "/home/luisaam/Pictures",
    #                                    "_dilation_max_pool", "recording_dilation_max_pool_100_no_ffcv")

    diverse_pooling_model_names = [
        "resnet50_spectral_pool", "resnet50_softpool", "resnet50_mixedpool", "resnet50_lippool",
        "vgg19_spectral_pool", "vgg19_softpool", "vgg19_mixedpool" "vgg19_lippool",
    ]
    # diverse_pooling_saturation_summary("saturation_diverse_pooling", diverse_pooling_model_names)
    save_folder = "/home/luisaam/Pictures"
    plot_diverse_pooling_results(save_folder)
    # plot_saturation_relationships(save_folder)
    # plotting_second_order_saturation_OS_accuracy(save_folder)

    # analysis_pooling_methods()
    # analysis_pooling_methods_fine_tuned()
    # analysis_pooling_methods_one_shot()
    # decide_type_of_model()
