#!/bin/bash
#
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_1_cifar10_rs.err" --output="kfac_optim_rf_1_cifar10_rs.output"  --job-name="Kfac_optim_rf_1_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "1" "normal" "kfac_optim_hyper" "1"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_2_cifar10_rs.err" --output="kfac_optim_rf_2_cifar10_rs.output" --job-name="Kfac_optim_rf_2_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "2" "normal" "kfac_optim_hyper" "1"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_3_cifar10_rs.err" --output="kfac_optim_rf_3_cifar10_rs.output"  --job-name="Kfac_optim_rf_3_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "3" "normal" "kfac_optim_hyper" "1"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_4_cifar10_rs.err" --output="kfac_optim_rf_4_cifar10_rs.output" --job-name="Kfac_optim_rf_4_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "4" "normal" "kfac_optim_hyper" "1"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_k6_cifar10_rs.err" --output="kfac_optim_rf_k6_cifar10_rs.output" --job-name="Kfac_optim_rf_k6_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k6" "normal" "kfac_optim_hyper" "1"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_k7_cifar10_rs.err" --output="kfac_optim_rf_k7_cifar10_rs.output" --job-name="Kfac_optim_rf_k7_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k7" "normal" "kfac_optim_hyper" "1"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_k8_cifar10_rs.err" --output="kfac_optim_rf_k8_cifar10_rs.output" --job-name="Kfac_optim_rf_k8_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k8" "normal" "kfac_optim_hyper" "1"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="kfac_optim_rf_k9_cifar10_rs.err" --output="kfac_optim_rf_k9_cifar10_rs.output" --job-name="Kfac_optim_rf_k9_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k9" "normal" "kfac_optim_hyper" "1"
##
##
##
##
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_1_cifar10_rs.err" --output="sam_optim_rf_1_cifar10_rs.output" --job-name="sam_optim_rf_1_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "1" "normal" "sam_optim_hyper" "2"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_2_cifar10_rs.err" --output="sam_optim_rf_2_cifar10_rs.output" --job-name="sam_optim_rf_2_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "2" "normal" "sam_optim_hyper" "2"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_3_cifar10_rs.err" --output="sam_optim_rf_3_cifar10_rs.output" --job-name="sam_optim_rf_3_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "3" "normal" "sam_optim_hyper" "2"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_4_cifar10_rs.err" --output="sam_optim_rf_4_cifar10_rs.output" --job-name="sam_optim_rf_4_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "4" "normal" "sam_optim_hyper" "2"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_k6_cifar10_rs.err" --output="sam_optim_rf_k6_cifar10_rs.output" --job-name="sam_optim_rf_k6_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k6" "normal" "sam_optim_hyper" "2"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_k7_cifar10_rs.err" --output="sam_optim_rf_k7_cifar10_rs.output" --job-name="sam_optim_rf_k7_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k7" "normal" "sam_optim_hyper" "2"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_k8_cifar10_rs.err" --output="sam_optim_rf_k8_cifar10_rs.output" --job-name="sam_optim_rf_k8_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k8" "normal" "sam_optim_hyper" "2"
#sbatch --nodes=1 --time=24:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk --error="sam_optim_rf_k9_cifar10_rs.err" --output="sam_optim_rf_k9_cifar10_rs.output"  --job-name="sam_optim_rf_k9_cifar10_rs" slurm_2nd_order.sh "cifar10" "resnet50" "k9" "normal" "sam_optim_hyper" "2"
#
#sbatch --nodes=1 --time=00:05:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="import_test.err" --gres=gpu:1 --output="import_test.output"  --job-name="import_test" slurm_run.sh

#sbatch --nodes=1 --time=03:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="pruning_imagenet_resnet34.err" --gres=gpu:1 --output="pruning_imagenet_resnet34.output"  --job-name="pruning_imagenet_resnet34" slurm_run.sh "resnet34"
#sbatch --nodes=1 --time=03:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="pruning_imagenet_legacy_seresnet34.err" --gres=gpu:1 --output="pruning_imagenet_legacy_seresnet34.output"  --job-name="pruning_imagenet_legacy_seresnet34" slurm_run.sh "legacy_seresnet34"
#sbatch --nodes=1 --time=03:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="pruning_imagenet_skresnet34.err" --gres=gpu:1 --output="pruning_imagenet_skresnet34.output"  --job-name="pruning_imagenet_skresnet34" slurm_run.sh "skresnet34"
#sbatch --nodes=1 --time=03:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="pruning_imagenet_mobilenetv2.err" --gres=gpu:1 --output="pruning_imagenet_mobilenetv2.output"  --job-name="pruning_imagenet_mobilenetv2" slurm_run.sh "mobilenetv2"
#sbatch --nodes=1 --time=03:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="pruning_imagenet_mobilenetv3.err" --gres=gpu:1 --output="pruning_imagenet_mobilenetv3.output"  --job-name="pruning_imagenet_mobilenetv3" slurm_run.sh "mobilenetv3"
#sbatch --nodes=1 --time=03:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="pruning_imagenet_efficientnet.err" --gres=gpu:1 --output="pruning_imagenet_efficientnet.output"  --job-name="pruning_imagenet_efficientnet" slurm_run.sh "efficientnet"

#"resnet_small" "small_imagenet" 2 3 "normal" 200 "recording_200" 1 1

#########################     small resnet         Small imagenet    ####################################

#sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="small_resnet_lv_8_small_imagenet.err" --gres=gpu:1 --output="small_resnet_lv_8_small_imagenet.output"  --job-name="small_resnet_lv_8_small_imagenet" slurm_run.sh "resnet_small" "small_imagenet" 1 8 "normal" 200 "recording_200" 1 1
#sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="small_resnet_lv_9_small_imagenet.err" --gres=gpu:1 --output="small_resnet_lv_9_small_imagenet.output"  --job-name="small_resnet_lv_9_small_imagenet" slurm_run.sh "resnet_small" "small_imagenet" 2 9 "normal" 200 "recording_200" 1 1
#sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="small_resnet_lv_10_small_imagenet.err" --gres=gpu:1 --output="small_resnet_lv_10_small_imagenet.output"  --job-name="small_resnet_lv_10_small_imagenet" slurm_run.sh "resnet_small" "small_imagenet" 1 10 "normal" 200 "recording_200" 1 1
#                                                   FFCV variants
#sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="small_resnet_lv_8_small_imagenet_ffcv.err" --gres=gpu:1 --output="small_resnet_lv_8_small_imagenet_ffcv.output"  --job-name="small_resnet_lv_8_small_imagenet_ffcv" slurm_run_ffcv.sh "resnet_small" "small_imagenet" 1 8 "normal" 200 "recording_200_ffcv" 1 1 "/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" "/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv"
#sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="small_resnet_lv_9_small_imagenet_ffcv.err" --gres=gpu:1 --output="small_resnet_lv_9_small_imagenet_ffcv.output"  --job-name="small_resnet_lv_9_small_imagenet_ffcv" slurm_run_ffcv.sh "resnet_small" "small_imagenet" 1 9 "normal" 200 "recording_200_ffcv" 1 1 "/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" "/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv"
#sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="small_resnet_lv_10_small_imagenet_ffcv.err" --gres=gpu:1 --output="small_resnet_lv_10_small_imagenet_ffcv.output"  --job-name="small_resnet_lv_10_small_imagenet_ffcv" slurm_run_ffcv.sh "resnet_small" "small_imagenet" 1 10 "normal" 200 "recording_200_ffcv" 1 1 "/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" "/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv"


############################## Resume small resnet #######################################################
#qsub -l h_rt=48:00:00 -l coproc_v100=1 -N "resume_training_Level_3_small_resnet_small_imagenet" resume_run.sh "resnet_small" "small_imagenet" 2 3 "normal" 200 "recording_200" 1 1 "/nobackup/sclaam/checkpoints/resnet_small_normal_small_imagenet_seed.0_rf_level_3_recording_200_test_acc_42.89.pth"
sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="resume_small_resnet_lv_3_small_imagenet.err" --gres=gpu:1 --output="resume_small_resnet_lv_3_small_imagenet.output"  --job-name="resume_small_resnet_lv_3_small_imagenet" slurm_run.sh "resnet_small" "small_imagenet" 1 3 "normal" 200 "recording_200" 1 1 "/jmain02/home/J2AD014/mtc03/lla98-mtc03/checkpoints/resnet_small_normal_small_imagenet_seed.0_rf_level_3_recording_200_test_acc_51.46.pth"
sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="resume_small_resnet_lv_5_small_imagenet.err" --gres=gpu:1 --output="resume_small_resnet_lv_5_small_imagenet.output"  --job-name="resume_small_resnet_lv_5_small_imagenet" slurm_run.sh "resnet_small" "small_imagenet" 1 5 "normal" 200 "recording_200" 1 1 "/jmain02/home/J2AD014/mtc03/lla98-mtc03/checkpoints/resnet_small_normal_small_imagenet_seed.0_rf_level_5_recording_200_test_acc_54.11.pth"
sbatch --nodes=1 --time=96:00:00 --partition=small  --mail-type=all --mail-user=sclaam@leeds.ac.uk --error="resume_small_resnet_lv_7_small_imagenet.err" --gres=gpu:1 --output="resume_small_resnet_lv_7_small_imagenet.output"  --job-name="resume_small_resnet_lv_7_small_imagenet" slurm_run.sh "resnet_small" "small_imagenet" 1 7 "normal" 200 "recording_200" 1 1 "/jmain02/home/J2AD014/mtc03/lla98-mtc03/checkpoints/resnet_small_normal_small_imagenet_seed.0_rf_level_7_recording_200_test_acc_43.93.pth"

