#!/bin/bash



## Trained

sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_3_trained.err" --output="torchessian_level_3_trained.out" --job-name="torchessian_level_3_trained" slurm_hessian.sh FFCV=0 NAME="trained" MODEL="resnet50" DATASET="cifar10" NUMW=4 RFL=3 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=90 N_BUFFER=2 SOLUTION="" EVAL_SIZE=5000
sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_4_trained.err" --output="torchessian_level_4_trained.out" --job-name="torchessian_level_4_trained" slurm_hessian.sh FFCV=0 NAME="trained" MODEL="resnet50" DATASET="cifar10" NUMW=4 RFL=4 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=90 N_BUFFER=90 SOLUTION="${HOME}/seeds_for_hessian/resnet_small_normal_small_imagenet_seed.1_rf_level_4_recording_200_no_ffcv_test_acc_60.47.pth" EVAL_SIZE=5000
sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_5_trained.err" --output="torchessian_level_5_trained.out" --job-name="torchessian_level_5_trained" slurm_hessian.sh FFCV=0 NAME="trained" MODEL="resnet50" DATASET="cifar10" NUMW=4 RFL=5 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=90 N_BUFFER=90 SOLUTION="${HOME}/seeds_for_hessian/resnet_small_normal_small_imagenet_seed.5_rf_level_5_recording_200_test_acc_61.97.pth" EVAL_SIZE=5000
#sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_6_trained.err" --output="torchessian_level_6_trained.out" --job-name="torchessian_level_6_trained" slurm_hessian.sh FFCV=0 NAME="trained_ffcv" MODEL="resnet_small" DATASET="small_imagenet" NUMW=4 RFL=6 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=300 N_BUFFER=2 SOLUTION="${HOME}/seeds_for_hessian/resnet_small_normal_small_imagenet_seed.3_rf_level_6_recording_200_ffcv_test_acc_57.83.pth" EVAL_SIZE=5000
#sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_7_trained.err" --output="torchessian_level_7_trained.out" --job-name="torchessian_level_7_trained" slurm_hessian.sh FFCV=0 NAME="trained" MODEL="resnet_small" DATASET="small_imagenet" NUMW=4 RFL=7 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=300 N_BUFFER=2 SOLUTION="${HOME}/seeds_for_hessian/resnet_small_normal_small_imagenet_seed.3_rf_level_7_recording_200_test_acc_51.66.pth" EVAL_SIZE=5000
#sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_8_trained.err" --output="torchessian_level_8_trained.out" --job-name="torchessian_level_8_trained" slurm_hessian.sh FFCV=0 NAME="trained" MODEL="resnet_small" DATASET="small_imagenet" NUMW=4 RFL=8 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=300 N_BUFFER=2 SOLUTION="${HOME}/seeds_for_hessian/resnet_small_normal_small_imagenet_seed.6_rf_level_8_recording_200_test_acc_49.49.pth" EVAL_SIZE=5000
#sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_9_trained.err" --output="torchessian_level_9_trained.out" --job-name="torchessian_level_9_trained" slurm_hessian.sh FFCV=0 NAME="trained" MODEL="resnet_small" DATASET="small_imagenet" NUMW=4 RFL=9 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=300 N_BUFFER=2 SOLUTION="${HOME}/seeds_for_hessian/resnet_small_normal_small_imagenet_seed.7_rf_level_9_recording_200_test_acc_45.04.pth" EVAL_SIZE=5000
#sbatch --nodes=1 --time=143:00:00 --partition=small --gres=gpu:1 --mail-type=ALL --mail-user=sclaam@leeds.ac.uk  --error="torchessian_level_10_trained.err" --output="torchessian_level_10_trained.out" --job-name="torchessian_level_10_trained" slurm_hessian.sh FFCV=0 NAME="trained_ffcv" MODEL="resnet_small" DATASET="small_imagenet" NUMW=4 RFL=10 TYPE=normal FOLDER=$SCRATCH/hessian_results FFCV_TRAIN="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/train_360_0.5_90.ffcv" FFCV_VAL="/jmain02/home/J2AD014/mtc03/lla98-mtc03/small_imagenet_ffcv/val_360_0.5_90.ffcv" DATA_FOLDER="${HOME}/datasets" METHOD="torchessian" BATCH_ONLY=0 N_EIGEN=300 N_BUFFER=2 SOLUTION="${HOME}/seeds_for_hessian/resnet_small_normal_small_imagenet_seed.4_rf_level_10_recording_200_no_ffcv_test_acc_39.98.pth" EVAL_SIZE=5000
